# Generated by Django 4.1.3 on 2024-04-17 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_menu_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='Description',
            new_name='description',
        ),
    ]
